[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_game = "C6eqnSPN75gz2if2e8M3H7xdz4WUX7kPfnDbmHxG9Ri5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kenny/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
