[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_game = "BGXHsoqm7cXC6PfAXcyPNuyNAzUgGs6iushSr2SJCP1v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kenny/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
